const images = {
  'ATL': require('../assets/images/team-logos/ATL_logo.png'),
  'BOS': require('../assets/images/team-logos/BOS_logo.png'),
  'BKN': require('../assets/images/team-logos/BKN_logo.png'),
  'CHA': require('../assets/images/team-logos/CHA_logo.png'),
  'CHI': require('../assets/images/team-logos/CHI_logo.png'),
  'CLE': require('../assets/images/team-logos/CLE_logo.png'),
  'DAL': require('../assets/images/team-logos/DAL_logo.png'),
  'DEN': require('../assets/images/team-logos/DEN_logo.png'),
  'DET': require('../assets/images/team-logos/DET_logo.png'),
  'GSW': require('../assets/images/team-logos/GSW_logo.png'),
  'HOU': require('../assets/images/team-logos/HOU_logo.png'),
  'IND': require('../assets/images/team-logos/IND_logo.png'),
  'LAC': require('../assets/images/team-logos/LAC_logo.png'),
  'LAL': require('../assets/images/team-logos/LAL_logo.png'),
  'MEM': require('../assets/images/team-logos/MEM_logo.png'),
  'MIA': require('../assets/images/team-logos/MIA_logo.png'),
  'MIL': require('../assets/images/team-logos/MIL_logo.png'),
  'MIN': require('../assets/images/team-logos/MIN_logo.png'),
  'NOP': require('../assets/images/team-logos/NOP_logo.png'),
  'NYK': require('../assets/images/team-logos/NYK_logo.png'),
  'OKC': require('../assets/images/team-logos/OKC_logo.png'),
  'ORL': require('../assets/images/team-logos/ORL_logo.png'),
  'PHI': require('../assets/images/team-logos/PHI_logo.png'),
  'PHX': require('../assets/images/team-logos/PHX_logo.png'),
  'POR': require('../assets/images/team-logos/POR_logo.png'),
  'SAC': require('../assets/images/team-logos/SAC_logo.png'),
  'SAS': require('../assets/images/team-logos/SAS_logo.png'),
  'TOR': require('../assets/images/team-logos/TOR_logo.png'),
  'UTA': require('../assets/images/team-logos/UTA_logo.png'),
  'WAS': require('../assets/images/team-logos/WAS_logo.png'),
};

export default images;
